const projects = [
  {
    id: "invictus-games-2025",
    title: "Invictus Games 2025",
    category: "Interactive Feature",
    tags: ["HTML", "CSS", "JavaScript", "CMS"],
    image: "images/Invictus-games.jpeg",
    award: "Silver — Best Website | Canadian Online Publishing Awards",
    year: "2025",
    client: "Legion Magazine / Canvet Publications",
    role: "Web Designer & Developer",
    url: "https://legionmagazine.com/features/Invictusgames2025/",
    gradient: "linear-gradient(135deg, #1a1a2e 0%, #16213e 50%, #0f3460 100%)",
    description: "An award-winning interactive feature built for Legion Magazine covering the Invictus Games 2025. This project earned a Silver award for Best Website at the Canadian Online Publishing Awards — one of the highest honours in Canadian digital publishing.",
    overview: "The Invictus Games is an international adaptive sports competition for wounded, injured, and sick armed services personnel. This feature was designed to bring their stories to life through immersive web design, combining multimedia storytelling with editorial content.",
    highlights: [
      "Won Silver — Best Website at the Canadian Online Publishing Awards",
      "Fully responsive, mobile-first interactive layout",
      "Integrated multimedia assets including photography and video",
      "Accessibility-compliant (WCAG/AODA) design and development",
      "Built and deployed through CMS with cross-device QA testing"
    ],
    tools: ["Figma", "HTML / CSS / JavaScript", "Adobe Photoshop", "Adobe After Effects", "CMS Publishing", "WCAG / AODA"]
  },
  {
    id: "legion-100th-anniversary",
    title: "Royal Canadian Legion — 100th Anniversary",
    category: "Interactive Experience",
    tags: ["HTML", "CSS", "JavaScript", "Multimedia"],
    year: "2024",
    client: "Royal Canadian Legion",
    role: "Web Designer & Developer",
    url: "https://www.legion.ca/ourstory/",
    gradient: "linear-gradient(135deg, #2d1b00 0%, #5c3a00 100%)",
    image: "images/RCL.jpeg",
    video: "images/RCL-video.mp4",
    description: "A centennial interactive experience celebrating 100 years of the Royal Canadian Legion. Designed to honour the history, sacrifice, and legacy of Canadian veterans through rich digital storytelling.",
    overview: "This milestone project marked the Legion's 100th anniversary with an immersive online experience. The design drew on archival photography, historical timelines, and multimedia content to guide visitors through a century of Canadian military history and community service.",
    highlights: [
      "Centennial milestone project for a major national institution",
      "Historical timeline with archival imagery and multimedia",
      "Interactive navigation designed for broad audience accessibility",
      "Collaborated with editorial and communications teams",
      "Optimised for performance across all devices"
    ],
    tools: ["Figma", "HTML / CSS / JavaScript", "Adobe Photoshop", "Adobe Illustrator", "CMS Publishing", "WCAG / AODA"]
  },
  {
    id: "the-scheldt-campaign",
    title: "The Scheldt Campaign",
    category: "Multimedia Storytelling",
    tags: ["HTML", "CSS", "JavaScript", "Editorial"],
    year: "2023",
    client: "Legion Magazine / Canvet Publications",
    role: "Web Designer & Developer",
    url: "https://legionmagazine.com/features/the-scheldt-campaign/",
    gradient: "linear-gradient(135deg, #0d1b0d 0%, #1a3a1a 100%)",
    image: "images/scheldt.jpeg",
    video: "images/scheldt.mp4",
    description: "An interactive historical feature detailing the Battle of the Scheldt during World War II — one of Canada's most significant and costly military operations.",
    overview: "The Battle of the Scheldt in autumn 1944 was crucial in opening the port of Antwerp, helping to supply Allied forces across Northwestern Europe. This feature combines historical narrative, photography, and interactive design to tell that story in a way that honours both accuracy and emotional resonance.",
    highlights: [
      "Deep-dive historical storytelling with editorial photography",
      "Custom interactive layout for long-form content",
      "Multimedia integration including maps and archival imagery",
      "Designed for readers with no prior knowledge of the campaign",
      "Cross-browser tested"
    ],
    tools: ["Figma", "HTML / CSS / JavaScript", "Adobe Photoshop", "Adobe InDesign", "CMS Publishing"]
  },
  {
    id: "rcaf-100",
    title: "RCAF — 100 Years",
    category: "Interactive Feature",
    tags: ["HTML", "CSS", "JavaScript", "Multimedia"],
    year: "2024",
    client: "Legion Magazine / Canvet Publications",
    role: "Web Designer & Developer",
    url: "https://legionmagazine.com/features/rcaf-100/",
    gradient: "linear-gradient(135deg, #1a0a2e 0%, #3d1c6e 100%)",
    image: "images/RCAF.jpeg",
    video: "images/RCAF.mp4",
    description: "An interactive centennial feature celebrating 100 years of the Royal Canadian Air Force, tracing its evolution from early biplanes to modern jet fighters.",
    overview: "From its founding in 1924 to its role in modern international operations, the RCAF's century of service is a story of innovation, courage, and sacrifice. This feature used rich visual design and interactive elements to make that history accessible and engaging for a broad readership.",
    highlights: [
      "Centennial feature with strong visual identity",
      "Timeline-driven layout tracing 100 years of aviation history",
      "Integration of archival and contemporary photography",
      "Responsive design optimised for desktop and mobile"
    ],
    tools: ["Figma", "HTML / CSS / JavaScript", "Adobe Photoshop", "Adobe Illustrator", "CMS Publishing"]
  },
  {
    id: "those-damn-women",
    title: "Those Damn Women",
    category: "Digital Storytelling",
    tags: ["HTML", "CSS", "JavaScript", "Editorial"],
    year: "2023",
    client: "Legion Magazine / Canvet Publications",
    role: "Web Designer & Developer",
    url: "https://legionmagazine.com/features/those-damn-women/",
    gradient: "linear-gradient(135deg, #2e0a0a 0%, #6e1c1c 100%)",
    image: "images/those-damn-women.jpeg",
    video: "images/those-damn-women.mp4",
    description: "A digital storytelling project shining a light on the extraordinary contributions of women during wartime — often overlooked, always essential.",
    overview: "\"Those Damn Women\" is an editorial feature that reclaims the stories of women who served, supported, and sacrificed during times of war. The design prioritised emotional impact, using bold typography, portraiture, and a narrative-first layout to give these voices the prominence they deserve.",
    highlights: [
      "Narrative-led design with editorial photography",
      "Bold typographic treatment to amplify subject matter",
      "Sensitive, accessible design for a broad readership",
      "Collaborative project with editorial and research teams",
      "Fully responsive with strong mobile reading experience"
    ],
    tools: ["Figma", "HTML / CSS / JavaScript", "Adobe Photoshop", "Adobe InDesign", "CMS Publishing"]
  },
  {
    id: "afghanistan",
    title: "Afghanistan — Canada's Longest War",
    category: "Long-form Feature",
    tags: ["HTML", "CSS", "JavaScript", "Multimedia"],
    year: "2022",
    client: "Legion Magazine / Canvet Publications",
    role: "Web Designer & Developer",
    url: "https://legionmagazine.com/afghanistan-canadas-longest-war-interactive-story/",
    gradient: "linear-gradient(135deg, #1a1500 0%, #3d3200 100%)",
    image: "images/Afghanistan-cover.jpeg",
    video: "images/Afghanistan.mp4",
    description: "An interactive long-form multimedia feature on Canada's mission in Afghanistan — the country's longest and most complex modern military engagement.",
    overview: "Canada's involvement in Afghanistan from 2001 to 2014 touched thousands of families across the country. This long-form feature was designed to document that mission with depth and care — combining first-person accounts, archival photography, maps, and video into a cohesive, immersive narrative.",
    highlights: [
      "Long-form interactive storytelling with video integration",
      "Complex multimedia layout managing multiple content types",
      "Custom scroll-based interactions for narrative pacing",
      "Archival photography and video editing for web delivery",
      "Recognised internally as a benchmark for multimedia features"
    ],
    tools: ["Figma", "HTML / CSS / JavaScript", "Adobe Photoshop", "Adobe Premiere Pro", "Adobe After Effects", "CMS Publishing"]
  },
  {
    id: "operation-husky",
    title: "Operation Husky — Sicily",
    category: "Interactive Feature",
    tags: ["HTML", "CSS", "JavaScript", "Historical"],
    year: "2023",
    client: "Legion Magazine / Canvet Publications",
    role: "Web Designer & Developer",
    url: "https://legionmagazine.com/operation-husky-the-allies-take-sicily-interactive-story/",
    gradient: "linear-gradient(135deg, #001a1a 0%, #003d3d 100%)",
    image: "images/sicily.jpeg",
    video: "images/sicily.mp4",
    description: "An interactive feature exploring Operation Husky — the Allied invasion of Sicily in 1943 and Canada's pivotal role in one of WWII's largest amphibious assaults.",
    overview: "Operation Husky was a turning point in the Second World War. Canada's contribution to the invasion of Sicily in July 1943 was significant — and largely untold. This feature brought that story to a new generation through interactive maps, archival imagery, and editorial narrative.",
    highlights: [
      "Interactive maps illustrating the Allied campaign across Sicily",
      "Archival photography and historical document integration",
      "Narrative structure guiding readers through key battle phases",
      "Designed for readers unfamiliar with WWII history",
      "Responsive layout with strong desktop and mobile performance"
    ],
    tools: ["Figma", "HTML / CSS / JavaScript", "Adobe Photoshop", "Adobe Illustrator", "CMS Publishing"]
  },
  {
    id: "korea-the-war-without-end",
    title: "Korea — The War Without End",
    category: "Multimedia Storytelling",
    tags: ["HTML", "CSS", "JavaScript", "Multimedia"],
    year: "2022",
    client: "Legion Magazine / Canvet Publications",
    role: "Web Designer & Developer",
    url: "https://legionmagazine.com/korea-the-war-without-end-interactive-story/",
    gradient: "linear-gradient(135deg, #0a0a1a 0%, #1a1a3d 100%)",
    image: "images/korea.jpeg",
    video: "images/korea.mp4",
    description: "A multimedia storytelling feature on the Korean War and its lasting impact — a conflict often called 'The Forgotten War', brought to life through immersive digital design.",
    overview: "The Korean War (1950–1953) saw over 26,000 Canadians serve, yet it remains one of the least-remembered conflicts in national memory. This feature aimed to change that — using multimedia storytelling to document the human cost and historical significance of Canada's involvement.",
    highlights: [
      "Multimedia-rich long-form feature with strong narrative arc",
      "Photography, video, and audio integrated into editorial layout",
      "Designed to engage readers with limited prior knowledge",
      "Scroll-paced storytelling for emotional engagement"
    ],
    tools: ["Figma", "HTML / CSS / JavaScript", "Adobe Photoshop", "Adobe Premiere Pro", "CMS Publishing"]
  },
  {
    id: "canada-and-the-great-war",
    title: "Canada & The Great War",
    category: "Interactive Feature",
    tags: ["HTML", "CSS", "JavaScript", "Historical"],
    year: "2022",
    client: "Legion Magazine / Canvet Publications",
    role: "Web Designer & Developer",
    url: "https://legionmagazine.com/features/canada-and-the-great-war-liberation/",
    gradient: "linear-gradient(135deg, #1a0d00 0%, #4a2800 100%)",
    image: "images/Canada-the-Great-War.jpeg",
    video: "images/Canada-the-Great-War.mp4",
    description: "An interactive feature covering Canada's defining role in the liberation campaigns of the First World War — from Vimy Ridge to the Hundred Days Offensive.",
    overview: "Canada's contribution to the First World War forged the nation's identity on the world stage. This feature traced the arc of Canada's involvement through key battles, pivotal moments, and the human stories behind them — designed to educate and move readers in equal measure.",
    highlights: [
      "Historical feature covering Canada's full WWI contribution",
      "Timeline-based interactive layout with archival imagery",
      "Editorial collaboration with historians and researchers",
      "Designed for educational and commemorative audiences",
      "Strong performance across devices"
    ],
    tools: ["Figma", "HTML / CSS / JavaScript", "Adobe Photoshop", "Adobe InDesign", "CMS Publishing"]
  },
  {
    id: "liberation-of-netherlands",
    title: "Liberation of the Netherlands",
    category: "Digital Storytelling",
    award: "Gold — Best Interactive Story | Canadian Online Publishing Awards 2020",
    tags: ["HTML", "CSS", "JavaScript", "Editorial"],
    year: "2023",
    client: "Legion Magazine / Canvet Publications",
    role: "Web Designer & Developer",
    url: "https://legionmagazine.com/features/liberation-of-netherlands/",
    gradient: "linear-gradient(135deg, #001a0d 0%, #003d1c 100%)",
    image: "images/netherlands.jpeg",
    video: "images/netherlands.mp4",
    description: "An interactive storytelling project on the liberation of the Netherlands during WWII — and the enduring bond between Canada and the Dutch people.",
    overview: "In 1945, Canadian forces liberated the Netherlands from Nazi occupation. The gratitude of the Dutch people toward Canada has lasted generations. This feature documented that liberation campaign and the profound relationship it created — a story of friendship as much as warfare.",
    highlights: [
      "Emotionally resonant design honouring a historic friendship",
      "Archival photography from the liberation campaign",
      "Editorial storytelling balancing history and human interest",
      "Featured testimonials and contemporary Dutch perspectives",
      "Fully responsive layout"
    ],
    tools: ["Figma", "HTML / CSS / JavaScript", "Adobe Photoshop", "Adobe InDesign", "CMS Publishing"]
  },
  {
    id: "the-october-crisis",
    title: "The October Crisis",
    category: "Interactive Feature",
    award: "Silver — Best Interactive Story | Canadian Online Publishing Awards 2020",
    tags: ["HTML", "CSS", "JavaScript", "Editorial"],
    year: "2020",
    client: "Legion Magazine / Canvet Publications",
    role: "Web Designer & Developer",
    url: "https://legionmagazine.com/features/theoctobercrisis/",
    gradient: "linear-gradient(135deg, #1a0000 0%, #4a0000 100%)",
    image: "images/october-crisis.jpeg",
    video: "images/october-crisis.mp4",
    description: "A historical interactive feature examining Canada's October Crisis of 1970 — the only peacetime invocation of the War Measures Act in Canadian history.",
    overview: "In October 1970, the FLQ kidnapped two government officials, triggering a constitutional crisis that changed Canada forever. This feature examined the events, decisions, and consequences of that month through an editorial lens — balancing historical analysis with compelling design.",
    highlights: [
      "Politically sensitive subject handled with editorial care",
      "Documentary-style design with archival news photography",
      "Timeline layout mapping the crisis day by day",
      "Strong typographic treatment for editorial gravitas",
      "Responsive and accessible across all platforms"
    ],
    tools: ["Figma", "HTML / CSS / JavaScript", "Adobe Photoshop", "Adobe InDesign", "CMS Publishing"]
  },
  {
    id: "canadas-ultimate-story",
    title: "Canada's Ultimate Story",
    category: "Corporate Website",
    tags: ["WordPress", "PHP", "CSS"],
    year: "2019 – Present",
    client: "Canvet Publications Ltd.",
    role: "Web Designer & Administrator",
    url: "https://canadasultimatestory.com/",
    gradient: "linear-gradient(135deg, #0a1628 0%, #1a3a5c 100%)",
    image: "images/CUS.jpg",
    video: "images/CUS.mp4",
    description: "A standalone magazine website for Canada's Ultimate Story — a publication by Canvet Publications Ltd. celebrating Canadian history, culture, and identity.",
    overview: "Canada's Ultimate Story is a premium magazine publication dedicated to telling the stories that define Canada. As Web Designer and Administrator, I designed and developed the site to reflect the editorial quality of the publication — clean, authoritative, and accessible across all devices.",
    highlights: [
      "Full website design and development for a standalone publication",
      "Editorial CMS publishing workflows and content management",
      "Responsive design optimised for desktop and mobile",
      "Consistent visual identity aligned with the print publication",
      "Ongoing administration and maintenance"
    ],
    tools: ["Figma", "HTML / CSS / JavaScript", "Adobe Creative Cloud"]
  },
  {
    id: "legion-magazine",
    title: "Legion Magazine",
    category: "Corporate Website",
    tags: ["WordPress", "PHP", "CSS", "WooCommerce"],
    year: "2019 – Present",
    client: "Canvet Publications Ltd.",
    role: "Web Designer & Administrator",
    url: "https://legionmagazine.com/",
    gradient: "linear-gradient(135deg, #1a1400 0%, #3d3000 100%)",
    image: "images/LM.jpg",
    video: "images/LM.mp4",
    description: "The corporate website for Legion Magazine — Canada's largest veterans' publication — featuring articles, multimedia stories, digital magazine content, and an integrated e-commerce store.",
    overview: "As Web Designer and Administrator at Canvet Publications, I have been responsible for the ongoing design, development, and management of legionmagazine.com since 2019. This includes the editorial site, interactive features, and the WooCommerce-powered subscription and retail store.",
    highlights: [
      "Ongoing web design, development, and administration since 2019",
      "Manages editorial CMS publishing workflows and QA testing",
      "Integrated WooCommerce store for subscriptions and products",
      "Accessibility compliance (WCAG / AODA) across all pages",
      "Cross-device optimisation and performance monitoring",
      "Launched and maintains all interactive storytelling features"
    ],
    tools: ["Figma", "WordPress", "WooCommerce", "PHP", "HTML / CSS / JavaScript", "Adobe Creative Cloud", "WCAG / AODA"]
  }
];
